/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BackGroundPanel.java
 *
 * Created on 15/06/2010, 14:19:26
 */

package view.game;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author nicolas
 */
public class BackGroundPanel extends javax.swing.JPanel {

    private BufferedImage image;

    /** Creates new form BackGroundPanel */
    public BackGroundPanel() {
        initComponents();
    }

    public BackGroundPanel(BufferedImage image) {
        initComponents();
        this.setImage(image);
    }

    public void setImage(BufferedImage image) {
        // Check not null.
        this.image = image;
    }

    @Override
    protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            if (this.image != null) {
                    Dimension size = this.getSize();
                    g.drawImage(this.image, 0, 0, size.width, size.height, this);
            }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
