package view.game;

import java.awt.Color;
import static view.game.MoneyConstants.*;

public class BudgetPanel extends javax.swing.JPanel {

    private static final Color OK_COLOR = new Color(0, 0, 0, 1.0F);
    private static final Color BAD_COLOR = new Color(1, 0, 0, 1.0F);

    /** Creates new form BudgetPanel */
    public BudgetPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgetBalanceLabel = new javax.swing.JLabel();

        budgetBalanceLabel.setFont(new java.awt.Font("Purisa", 0, 18));
        budgetBalanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        budgetBalanceLabel.setText("jLabel1");
        budgetBalanceLabel.setBorder(null);
        budgetBalanceLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        budgetBalanceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(budgetBalanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(budgetBalanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setMoneyBalance(int balance){
       if (balance > 0)
           this.budgetBalanceLabel.setForeground(OK_COLOR);
       else
           this.budgetBalanceLabel.setForeground(BAD_COLOR);

        this.budgetBalanceLabel.setText(MONEY + ": " + MONEY_SYMBOL + " " + balance);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel budgetBalanceLabel;
    // End of variables declaration//GEN-END:variables

}
