package view.game;

import javax.swing.JPanel;

public class GamePanel extends javax.swing.JPanel {
    
    /** Creates new form GamePanel */
    public GamePanel(GroundPanelContainer groundPanelContainer) {
        this.groundPanelContainer = groundPanelContainer;
        initComponents();
    }
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolPanel = new javax.swing.JPanel();
        jScrollPane1 = this.groundPanelContainer;
        budgetPanel = new view.game.BudgetPanel();
        toolBarPanel = new view.game.ToolBarPanel();

        setFont(new java.awt.Font("Purisa", 0, 13));
        setPreferredSize(new java.awt.Dimension(850, 650));

        toolPanel.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(toolBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolBarPanel, 0, 0, Short.MAX_VALUE)
                    .addComponent(budgetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(toolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public ToolBarPanel getToolBarPanel(){
        return this.toolBarPanel;
    }

    public void setToolPanel(JPanel panel){
        this.toolPanel.removeAll();
        this.toolPanel.add(panel);
        this.toolPanel.revalidate();
    }

    public GroundPanelContainer getGroundPanelContainer(){
        return this.groundPanelContainer;
    }

    public BudgetPanel getBudgetPanel(){
        return this.budgetPanel;
    }

    private GroundPanelContainer groundPanelContainer;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.game.BudgetPanel budgetPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private view.game.ToolBarPanel toolBarPanel;
    private javax.swing.JPanel toolPanel;
    // End of variables declaration//GEN-END:variables
}
