package view.game;

import static model.utils.ArgumentUtils.checkNotNull;

import java.awt.event.ActionListener;

import javax.swing.JComboBox;
import javax.swing.JScrollPane;

import view.game.ground.StaticGroundPanel;

public class GroundSelectionPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private StaticGroundPanel groundPanel2;

    public GroundSelectionPanel() {
        initComponents();
    }
    
    public JComboBox getGroundCombo(){
        return this.groundCombo;
    }

    public BudgetPanel getBudgetPanel(){
        return this.budgetPanel;
    }

    public StaticGroundPanel getGroundPanel(){
        return this.groundPanel2;
    }
    
	public void setGroundPanel(StaticGroundPanel groundPanel) {
		checkNotNull(groundPanel, "ground panel");
		this.groundPanel2 = groundPanel;

		this.groundScrollPane = new JScrollPane(
				JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
				JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
		this.groundScrollPane.setViewportView(this.groundPanel2);

		this.groundPanel.removeAll();
		this.groundPanel.add(this.groundScrollPane);
		this.groundPanel.revalidate();
	}

    public void addRentButtonActionListener(ActionListener al){
        this.rentButton.addActionListener(al);
    }

    public void addBuyButtonActionListener(ActionListener al){
        this.buyButton.addActionListener(al);
    }

    public void addBackButtonActionListener(ActionListener al){
        this.backButton.addActionListener(al);
    }

    public void setRentButtonEnabled(boolean aFlag){
        this.rentButton.setEnabled(aFlag);
    }

    public void setBuyButtonEnabled(boolean aFlag){
        this.buyButton.setEnabled(aFlag);
    }

    public void setRentPrice(int price){
        this.rentPriceLabel.setText(MoneyConstants.getMoneyString(price));
    }

    public void setPurchasePrice(int price){
        this.purchasePriceLabel.setText(MoneyConstants.getMoneyString(price));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittleLabel = new javax.swing.JLabel();
        groundSelectionElements = new javax.swing.JPanel();
        groundCombo = new javax.swing.JComboBox();
        buttonsPanel = new javax.swing.JPanel();
        buyButton = new javax.swing.JButton();
        rentButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        budgetPanel = new view.game.BudgetPanel();
        labelsPanel = new javax.swing.JPanel();
        purchasePriceLabel2 = new javax.swing.JLabel();
        purchasePriceLabel = new javax.swing.JLabel();
        rentPriceLabel2 = new javax.swing.JLabel();
        rentPriceLabel = new javax.swing.JLabel();
        groundPanel = new javax.swing.JPanel();
        groundScrollPane = new javax.swing.JScrollPane();

        tittleLabel.setFont(new java.awt.Font("Purisa", 0, 26));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("Ground Selection");

        buttonsPanel.setLayout(new java.awt.GridLayout(1, 0));

        buyButton.setFont(new java.awt.Font("Purisa", 0, 13));
        buyButton.setText("Buy");
        buttonsPanel.add(buyButton);

        rentButton.setFont(new java.awt.Font("Purisa", 0, 13));
        rentButton.setText("Rent");
        buttonsPanel.add(rentButton);

        backButton.setFont(new java.awt.Font("Purisa", 0, 13));
        backButton.setText("Back");
        buttonsPanel.add(backButton);

        labelsPanel.setLayout(new java.awt.GridLayout(2, 2));

        purchasePriceLabel2.setFont(new java.awt.Font("Purisa", 0, 13));
        purchasePriceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchasePriceLabel2.setText("Purchase price:");
        labelsPanel.add(purchasePriceLabel2);

        purchasePriceLabel.setFont(new java.awt.Font("Purisa", 0, 13));
        purchasePriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsPanel.add(purchasePriceLabel);

        rentPriceLabel2.setFont(new java.awt.Font("Purisa", 0, 13));
        rentPriceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentPriceLabel2.setText("Rent price:");
        labelsPanel.add(rentPriceLabel2);

        rentPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsPanel.add(rentPriceLabel);

        javax.swing.GroupLayout groundSelectionElementsLayout = new javax.swing.GroupLayout(groundSelectionElements);
        groundSelectionElements.setLayout(groundSelectionElementsLayout);
        groundSelectionElementsLayout.setHorizontalGroup(
            groundSelectionElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groundCombo, 0, 279, Short.MAX_VALUE)
            .addComponent(budgetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
            .addComponent(labelsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );
        groundSelectionElementsLayout.setVerticalGroup(
            groundSelectionElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groundSelectionElementsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groundCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(budgetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        groundPanel.setLayout(new java.awt.BorderLayout());

        groundScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        groundPanel.add(groundScrollPane, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tittleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(groundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(groundSelectionElements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tittleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(groundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(groundSelectionElements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private view.game.BudgetPanel budgetPanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton buyButton;
    private javax.swing.JComboBox groundCombo;
    private javax.swing.JPanel groundPanel;
    private javax.swing.JScrollPane groundScrollPane;
    private javax.swing.JPanel groundSelectionElements;
    private javax.swing.JPanel labelsPanel;
    private javax.swing.JLabel purchasePriceLabel;
    private javax.swing.JLabel purchasePriceLabel2;
    private javax.swing.JButton rentButton;
    private javax.swing.JLabel rentPriceLabel;
    private javax.swing.JLabel rentPriceLabel2;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables

}
