package view.game;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;

import static model.utils.ArgumentUtils.*;

public class GroundSelectionPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private GroundPanelContainer groundPanelContainer;

    public GroundSelectionPanel(){
    	initComponents();
    }
    
    public GroundSelectionPanel(GroundPanelContainer groundPanelContainer) {
        initComponents();
        checkNotNull(groundPanelContainer, "groundPanelContainer");
        this.setGroundPanelContainer(groundPanelContainer);
    }
    
    public JComboBox getGroundCombo(){
        return this.groundCombo;
    }

    public BudgetPanel getBudgetPanel(){
        return this.budgetPanel;
    }

    public GroundPanelContainer getGroundPanelContainer(){
        return this.groundPanelContainer;
    }
    
    public void setGroundPanelContainer(GroundPanelContainer gamePanel){
    	this.groundPanelContainer = gamePanel;
        this.groundPanel.removeAll();
        this.groundScrollPane = this.groundPanelContainer;
        this.groundPanel.add(this.groundScrollPane);
        this.groundPanel.revalidate();
    }

    public void addRentButtonActionListener(ActionListener al){
        this.rentButton.addActionListener(al);
    }

    public void addBuyButtonActionListener(ActionListener al){
        this.buyButton.addActionListener(al);
    }

    public void addBackButtonActionListener(ActionListener al){
        this.backButton.addActionListener(al);
    }

    public void setRentPrice(int price){
        this.rentPriceLabel.setText(MoneyConstants.getMoneyString(price));
    }

    public void setPurchasePrice(int price){
        this.purchasePriceLabel.setText(MoneyConstants.getMoneyString(price));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tittleLabel = new javax.swing.JLabel();
        groundSelectionElements = new javax.swing.JPanel();
        groundCombo = new javax.swing.JComboBox();
        buttonsPanel = new javax.swing.JPanel();
        buyButton = new javax.swing.JButton();
        rentButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        budgetPanel = new view.game.BudgetPanel();
        labelsPanel = new javax.swing.JPanel();
        purchasePriceLabel2 = new javax.swing.JLabel();
        purchasePriceLabel = new javax.swing.JLabel();
        rentPriceLabel2 = new javax.swing.JLabel();
        rentPriceLabel = new javax.swing.JLabel();
        groundPanel = new javax.swing.JPanel();
        groundScrollPane = new javax.swing.JScrollPane();

        setLayout(new java.awt.GridBagLayout());

        tittleLabel.setFont(new java.awt.Font("Purisa", 0, 26));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("Ground Selection");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 12);
        add(tittleLabel, gridBagConstraints);

        buttonsPanel.setLayout(new java.awt.GridLayout(1, 0));

        buyButton.setFont(new java.awt.Font("Purisa", 0, 13));
        buyButton.setText("Buy");
        buttonsPanel.add(buyButton);

        rentButton.setFont(new java.awt.Font("Purisa", 0, 13));
        rentButton.setText("Rent");
        buttonsPanel.add(rentButton);

        backButton.setFont(new java.awt.Font("Purisa", 0, 13));
        backButton.setText("Back");
        buttonsPanel.add(backButton);

        labelsPanel.setLayout(new java.awt.GridLayout(2, 2));

        purchasePriceLabel2.setFont(new java.awt.Font("Purisa", 0, 13));
        purchasePriceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchasePriceLabel2.setText("Purchase price:");
        labelsPanel.add(purchasePriceLabel2);

        purchasePriceLabel.setFont(new java.awt.Font("Purisa", 0, 13));
        purchasePriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsPanel.add(purchasePriceLabel);

        rentPriceLabel2.setFont(new java.awt.Font("Purisa", 0, 13));
        rentPriceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentPriceLabel2.setText("Rent price:");
        labelsPanel.add(rentPriceLabel2);

        rentPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsPanel.add(rentPriceLabel);

        javax.swing.GroupLayout groundSelectionElementsLayout = new javax.swing.GroupLayout(groundSelectionElements);
        groundSelectionElements.setLayout(groundSelectionElementsLayout);
        groundSelectionElementsLayout.setHorizontalGroup(
            groundSelectionElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groundCombo, 0, 279, Short.MAX_VALUE)
            .addComponent(budgetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
            .addComponent(labelsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );
        groundSelectionElementsLayout.setVerticalGroup(
            groundSelectionElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groundSelectionElementsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groundCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 12, 12);
        add(groundSelectionElements, gridBagConstraints);

        groundPanel.setLayout(new java.awt.BorderLayout());

        groundScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        groundPanel.add(groundScrollPane, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 245;
        gridBagConstraints.ipady = 234;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 12);
        add(groundPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private view.game.BudgetPanel budgetPanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton buyButton;
    private javax.swing.JComboBox groundCombo;
    private javax.swing.JPanel groundPanel;
    private javax.swing.JScrollPane groundScrollPane;
    private javax.swing.JPanel groundSelectionElements;
    private javax.swing.JPanel labelsPanel;
    private javax.swing.JLabel purchasePriceLabel;
    private javax.swing.JLabel purchasePriceLabel2;
    private javax.swing.JButton rentButton;
    private javax.swing.JLabel rentPriceLabel;
    private javax.swing.JLabel rentPriceLabel2;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables

}
