package view.game;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;

public class GroundSelectionPanel extends javax.swing.JPanel {

    private GroundPanelContainer groundPanelContainer;

    public GroundSelectionPanel(GroundPanelContainer groundPanelContainer) {
        // TODO check not null.
        this.groundPanelContainer = groundPanelContainer;
        initComponents();
    }

    public JComboBox getGroundCombo(){
        return this.groundCombo;
    }

    public BudgetPanel getBudgetPanel(){
        return this.budgetPanel;
    }

    public GroundPanelContainer getGroundPanel(){
        return this.groundPanelContainer;
    }

    public void addRentButtonActionListener(ActionListener al){
        this.rentButton.addActionListener(al);
    }

    public void addBuyButtonActionListener(ActionListener al){
        this.buyButton.addActionListener(al);
    }

    public void addBackButtonActionListener(ActionListener al){
        this.backButton.addActionListener(al);
    }

    public void setRentPrice(int price){
        this.rentPriceLabel.setText(MoneyConstants.getMoneyString(price));
    }

    public void setPurchasePrice(int price){
        this.purchasePriceLabel.setText(MoneyConstants.getMoneyString(price));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittleLabel = new javax.swing.JLabel();
        groundCombo = new javax.swing.JComboBox();
        buttonsPanel = new javax.swing.JPanel();
        buyButton = new javax.swing.JButton();
        rentButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        groundPanel = this.groundPanelContainer;
        budgetPanel = new view.game.BudgetPanel();
        labelsPanel = new javax.swing.JPanel();
        purchasePriceLabel2 = new javax.swing.JLabel();
        purchasePriceLabel = new javax.swing.JLabel();
        rentPriceLabel2 = new javax.swing.JLabel();
        rentPriceLabel = new javax.swing.JLabel();

        tittleLabel.setFont(new java.awt.Font("Purisa", 0, 26)); // NOI18N
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("Ground Selection");

        buttonsPanel.setLayout(new java.awt.GridLayout());

        buyButton.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        buyButton.setText("Buy");
        buttonsPanel.add(buyButton);

        rentButton.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        rentButton.setText("Rent");
        buttonsPanel.add(rentButton);

        backButton.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        backButton.setText("Back");
        buttonsPanel.add(backButton);

        labelsPanel.setLayout(new java.awt.GridLayout(2, 2));

        purchasePriceLabel2.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        purchasePriceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchasePriceLabel2.setText("Purchase price:");
        labelsPanel.add(purchasePriceLabel2);

        purchasePriceLabel.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        purchasePriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsPanel.add(purchasePriceLabel);

        rentPriceLabel2.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        rentPriceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentPriceLabel2.setText("Rent price:");
        labelsPanel.add(rentPriceLabel2);

        rentPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsPanel.add(rentPriceLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(groundPanel)
                    .addComponent(groundCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tittleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(budgetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(groundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groundCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private view.game.BudgetPanel budgetPanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton buyButton;
    private javax.swing.JComboBox groundCombo;
    private javax.swing.JScrollPane groundPanel;
    private javax.swing.JPanel labelsPanel;
    private javax.swing.JLabel purchasePriceLabel;
    private javax.swing.JLabel purchasePriceLabel2;
    private javax.swing.JButton rentButton;
    private javax.swing.JLabel rentPriceLabel;
    private javax.swing.JLabel rentPriceLabel2;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables

}
