package view.game;

import java.awt.image.BufferedImage;
import javax.swing.JButton;
import javax.swing.JComboBox;

public class LineElementsMarketPanel extends javax.swing.JPanel {

    public LineElementsMarketPanel() {
        initComponents();
    }

    public JComboBox getBuyCombo(){
        return this.lineElementBuyCombo;
    }

    public void setLineElementType(String type){
        this.lineElementTypeLabel.setText(type);
    }

    public void setLineElementImage(BufferedImage image){
        this.lineElementPreview.setImage(image);
    }

    public JButton getSellButton(){
        return this.sellButton;
    }

    public JButton getMoveButton(){
        return this.moveButton;
    }

    public JButton getCancelButton(){
        return this.cancelToolButton;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        prodLineLabel = new javax.swing.JLabel();
        lineElementBuyCombo = new javax.swing.JComboBox();
        lineElementPreview = new view.game.BackGroundPanel();
        lineElementTypeLabel = new javax.swing.JLabel();
        toolsLabel = new javax.swing.JLabel();
        buttonsExternalPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        sellButton = new javax.swing.JButton();
        moveButton = new javax.swing.JButton();
        cancelToolButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(227, 539));
        setMinimumSize(new java.awt.Dimension(227, 539));
        setPreferredSize(new java.awt.Dimension(227, 539));

        titleLabel.setFont(new java.awt.Font("Purisa", 0, 18));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Line Elements");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        prodLineLabel.setFont(new java.awt.Font("Purisa", 0, 13));
        prodLineLabel.setText("Production line elements:");

        lineElementBuyCombo.setFont(new java.awt.Font("Purisa", 0, 13));

        javax.swing.GroupLayout lineElementPreviewLayout = new javax.swing.GroupLayout(lineElementPreview);
        lineElementPreview.setLayout(lineElementPreviewLayout);
        lineElementPreviewLayout.setHorizontalGroup(
            lineElementPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        lineElementPreviewLayout.setVerticalGroup(
            lineElementPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lineElementTypeLabel.setFont(new java.awt.Font("Purisa", 0, 13));
        lineElementTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lineElementTypeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        toolsLabel.setFont(new java.awt.Font("Purisa", 0, 13));
        toolsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        toolsLabel.setText("Tools:");

        buttonsPanel.setLayout(new java.awt.GridLayout(1, 3));

        sellButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smallSell.png"))); // NOI18N
        sellButton.setToolTipText("Sell line element");
        buttonsPanel.add(sellButton);

        moveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smallMove.png"))); // NOI18N
        buttonsPanel.add(moveButton);

        cancelToolButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smallCancel.png"))); // NOI18N
        buttonsPanel.add(cancelToolButton);

        javax.swing.GroupLayout buttonsExternalPanelLayout = new javax.swing.GroupLayout(buttonsExternalPanel);
        buttonsExternalPanel.setLayout(buttonsExternalPanelLayout);
        buttonsExternalPanelLayout.setHorizontalGroup(
            buttonsExternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsExternalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        buttonsExternalPanelLayout.setVerticalGroup(
            buttonsExternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsExternalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lineElementPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodLineLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(lineElementBuyCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 203, Short.MAX_VALUE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonsExternalPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lineElementTypeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(toolsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prodLineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lineElementBuyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lineElementPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lineElementTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toolsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsExternalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsExternalPanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelToolButton;
    private javax.swing.JComboBox lineElementBuyCombo;
    private view.game.BackGroundPanel lineElementPreview;
    private javax.swing.JLabel lineElementTypeLabel;
    private javax.swing.JButton moveButton;
    private javax.swing.JLabel prodLineLabel;
    private javax.swing.JButton sellButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel toolsLabel;
    // End of variables declaration//GEN-END:variables
}
