/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NullToolBarPanel.java
 *
 * Created on 24/06/2010, 00:34:13
 */

package view.game;

public class NullToolBarPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	/** Creates new form NullToolBarPanel */
    public NullToolBarPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(227, 539));
        setMinimumSize(new java.awt.Dimension(227, 539));
        setPreferredSize(new java.awt.Dimension(227, 539));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
