package view.game;

import static view.game.MoneyConstants.MONEY_SYMBOL;

import java.awt.event.ActionListener;
import javax.swing.JButton;

import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTable;

public class RawMaterialsMarketPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	/** Creates new form RawMaterialsMarketPanel */
    public RawMaterialsMarketPanel() {
        initComponents();
    }

    public JTable getStockTable(){
        return this.rawMaterialsStockTable;
    }

    public JComboBox getBuyCombo(){
        return this.buyCombo;
    }

    public JSpinner getQuantitySpinner(){
        return this.quantitySpinner;
    }
    
    public void setRawMaterialPrice(int price){
        this.rawMaterialPriceLabel.setText(MONEY_SYMBOL + price);
    }

    public void setBuyButtonActionListener(ActionListener al){
        this.buyButton.addActionListener(al);
    }

    public JButton getBuyButton(){
        return this.buyButton;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rawMaterialsStockTable = new javax.swing.JTable();
        storageAreaLabel = new javax.swing.JLabel();
        rawMaterialsStockLabel = new javax.swing.JLabel();
        rawMaterialsMarketLabel = new javax.swing.JLabel();
        buyCombo = new javax.swing.JComboBox();
        buyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        quantitySpinner = new javax.swing.JSpinner();
        rawMaterialPriceLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(227, 539));
        setMinimumSize(new java.awt.Dimension(227, 539));
        setPreferredSize(new java.awt.Dimension(227, 539));

        rawMaterialsStockTable.setFont(new java.awt.Font("Purisa", 0, 13));
        rawMaterialsStockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rawMaterialsStockTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(rawMaterialsStockTable);

        storageAreaLabel.setFont(new java.awt.Font("Purisa", 0, 18));
        storageAreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storageAreaLabel.setText("Storage Area");

        rawMaterialsStockLabel.setFont(new java.awt.Font("Purisa", 0, 13));
        rawMaterialsStockLabel.setText("Raw materials in stock:");

        rawMaterialsMarketLabel.setFont(new java.awt.Font("Purisa", 0, 13));
        rawMaterialsMarketLabel.setText("Raw materials market:");

        buyCombo.setFont(new java.awt.Font("Purisa", 0, 13));
        buyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buyButton.setFont(new java.awt.Font("Purisa", 0, 13));
        buyButton.setText("Buy");

        quantitySpinner.setFont(new java.awt.Font("Purisa", 0, 13));

        rawMaterialPriceLabel.setFont(new java.awt.Font("Purisa", 0, 18));
        rawMaterialPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rawMaterialPriceLabel.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rawMaterialPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quantitySpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(rawMaterialPriceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(storageAreaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buyCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 203, Short.MAX_VALUE)
                            .addComponent(rawMaterialsMarketLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(rawMaterialsStockLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(buyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storageAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(rawMaterialsStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rawMaterialsMarketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JComboBox buyCombo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JLabel rawMaterialPriceLabel;
    private javax.swing.JLabel rawMaterialsMarketLabel;
    private javax.swing.JLabel rawMaterialsStockLabel;
    private javax.swing.JTable rawMaterialsStockTable;
    private javax.swing.JLabel storageAreaLabel;
    // End of variables declaration//GEN-END:variables

}
