package view.game;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTable;

import static view.game.MoneyConstants.*;

public class RawMaterialsMarketPanel extends javax.swing.JPanel {

    /** Creates new form RawMaterialsMarketPanel */
    public RawMaterialsMarketPanel() {
        initComponents();
    }

    public JTable getStockTable(){
        return this.rawMaterialsStockTable;
    }

    public JComboBox getRawMaterialBuyCombo(){
        return this.rawMaterialBuyCombo;
    }

    public JSpinner getRawMaterialSizeSpinner(){
        return this.rawMaterialSizeSpinner;
    }
    
    public void setRawMaterialPrice(int price){
        this.rawMaterialPriceLabel.setText(MONEY_SYMBOL + price);
    }

    public void setBuyButtonActionListener(ActionListener al){
        this.buyButton.addActionListener(al);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rawMaterialsStockTable = new javax.swing.JTable();
        storageAreaLabel = new javax.swing.JLabel();
        rawMaterialsStockLabel = new javax.swing.JLabel();
        rawMaterialsMarketLabel = new javax.swing.JLabel();
        rawMaterialBuyCombo = new javax.swing.JComboBox();
        rawMaterialSizeSpinner = new javax.swing.JSpinner();
        rawMaterialPriceLabel = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();

        rawMaterialsStockTable.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        rawMaterialsStockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(rawMaterialsStockTable);

        storageAreaLabel.setFont(new java.awt.Font("Purisa", 0, 18)); // NOI18N
        storageAreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storageAreaLabel.setText("Storage Area");

        rawMaterialsStockLabel.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        rawMaterialsStockLabel.setText("Raw materials in stock:");

        rawMaterialsMarketLabel.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        rawMaterialsMarketLabel.setText("Raw materials market:");

        rawMaterialBuyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rawMaterialPriceLabel.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        rawMaterialPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rawMaterialPriceLabel.setText("jLabel3");

        buyButton.setFont(new java.awt.Font("Purisa", 0, 13)); // NOI18N
        buyButton.setText("Buy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(storageAreaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rawMaterialSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rawMaterialPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rawMaterialBuyCombo, 0, 185, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rawMaterialsMarketLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(rawMaterialsStockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storageAreaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rawMaterialsStockLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rawMaterialsMarketLabel)
                .addGap(18, 18, 18)
                .addComponent(rawMaterialBuyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rawMaterialSizeSpinner)
                    .addComponent(rawMaterialPriceLabel))
                .addGap(18, 18, 18)
                .addComponent(buyButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox rawMaterialBuyCombo;
    private javax.swing.JLabel rawMaterialPriceLabel;
    private javax.swing.JSpinner rawMaterialSizeSpinner;
    private javax.swing.JLabel rawMaterialsMarketLabel;
    private javax.swing.JLabel rawMaterialsStockLabel;
    private javax.swing.JTable rawMaterialsStockTable;
    private javax.swing.JLabel storageAreaLabel;
    // End of variables declaration//GEN-END:variables

}
