package view.game;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JSpinner;

public class ResearchLabPanel extends javax.swing.JPanel {

    public ResearchLabPanel() {
        initComponents();
    }

    public JSpinner getDailyFundingSpinner(){
        return this.dailyFundingSpinner;
    }

    public JComboBox geTechnologyCombo(){
        return this.technologyCombo;
    }

    public JButton getResearchButton(){
        return this.researchButton;
    }

    public void setTechnologyPrice(int price){
        this.technologyPrice.setText(MoneyConstants.MONEY_SYMBOL + price);
    }

    public void setTechnologyInfo(String info){
        this.technologyInfo.setText(info);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittleLabel = new javax.swing.JLabel();
        dailyFundingLabel = new javax.swing.JLabel();
        technologiesResearchLabel = new javax.swing.JLabel();
        technologyCombo = new javax.swing.JComboBox();
        dailyFundingSpinner = new javax.swing.JSpinner();
        researchPanel = new javax.swing.JPanel();
        researchButton = new javax.swing.JButton();
        technologyPrice = new javax.swing.JLabel();
        technologyInfoScrollPane = new javax.swing.JScrollPane();
        technologyInfo = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(227, 539));
        setMinimumSize(new java.awt.Dimension(227, 539));
        setPreferredSize(new java.awt.Dimension(227, 539));

        tittleLabel.setFont(new java.awt.Font("Purisa", 0, 18));
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("Research lab");
        tittleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dailyFundingLabel.setFont(new java.awt.Font("Purisa", 0, 13));
        dailyFundingLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dailyFundingLabel.setText("Daily funding:");

        technologiesResearchLabel.setFont(new java.awt.Font("Purisa", 0, 13));
        technologiesResearchLabel.setText("Technologies research:");

        technologyCombo.setFont(new java.awt.Font("Purisa", 0, 13));
        technologyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        dailyFundingSpinner.setFont(new java.awt.Font("Purisa", 0, 13));

        researchPanel.setLayout(new java.awt.GridLayout(1, 2));

        researchButton.setFont(new java.awt.Font("Purisa", 0, 13));
        researchButton.setText("Research");
        researchPanel.add(researchButton);

        technologyPrice.setFont(new java.awt.Font("Purisa", 0, 13));
        technologyPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        technologyPrice.setText("jLabel1");
        technologyPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        researchPanel.add(technologyPrice);

        technologyInfo.setColumns(20);
        technologyInfo.setFont(new java.awt.Font("Purisa", 0, 13));
        technologyInfo.setRows(5);
        technologyInfoScrollPane.setViewportView(technologyInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dailyFundingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addGap(11, 11, 11))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(technologiesResearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(technologyCombo, 0, 205, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(technologyInfoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(researchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dailyFundingSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dailyFundingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dailyFundingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(technologiesResearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(technologyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(technologyInfoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(researchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dailyFundingLabel;
    private javax.swing.JSpinner dailyFundingSpinner;
    private javax.swing.JButton researchButton;
    private javax.swing.JPanel researchPanel;
    private javax.swing.JLabel technologiesResearchLabel;
    private javax.swing.JComboBox technologyCombo;
    private javax.swing.JTextArea technologyInfo;
    private javax.swing.JScrollPane technologyInfoScrollPane;
    private javax.swing.JLabel technologyPrice;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables

}
