package view.game;

import javax.swing.JButton;
import javax.swing.JToggleButton;

public class ToolBarPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	/** Creates new form ToolBarPanel */
    public ToolBarPanel() {
        initComponents();
    }

    public JButton getLineElementsMarketButton() {
        return this.lineElementsMarket;
    }

    public JButton getRawMaterialsMarketButton() {
        return this.rawMaterialsMarket;
    }

    public JButton getValidProductionLinesButton() {
        return this.validProductionLines;
    }

    public JButton getLabButton() {
        return this.lab;
    }

    public JButton getPricesButton(){
        return this.pricesButton;
    }

    public JButton getWarehouseInformationButton(){
        return this.info;
    }

    public JButton getSellButton() {
        return this.sell;
    }

    public JToggleButton getPauseButton() {
        return this.pause;
    }

    public JToggleButton getPlayButton() {
        return this.play;
    }

    public JButton getExitButton() {
        return this.exit;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        info = new javax.swing.JButton();
        lineElementsMarket = new javax.swing.JButton();
        rawMaterialsMarket = new javax.swing.JButton();
        validProductionLines = new javax.swing.JButton();
        pricesButton = new javax.swing.JButton();
        sell = new javax.swing.JButton();
        lab = new javax.swing.JButton();
        play = new javax.swing.JToggleButton();
        pause = new javax.swing.JToggleButton();
        exit = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WarehouseInfo.png"))); // NOI18N
        info.setToolTipText("Warehouse information");
        info.setFocusable(false);
        info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        info.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(info);

        lineElementsMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Construction.png"))); // NOI18N
        lineElementsMarket.setToolTipText("Construction");
        lineElementsMarket.setFocusable(false);
        lineElementsMarket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lineElementsMarket.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(lineElementsMarket);

        rawMaterialsMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rawMaterialcart.png"))); // NOI18N
        rawMaterialsMarket.setToolTipText("Raw materials market");
        rawMaterialsMarket.setFocusable(false);
        rawMaterialsMarket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rawMaterialsMarket.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(rawMaterialsMarket);

        validProductionLines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/validSequences.png"))); // NOI18N
        validProductionLines.setToolTipText("Valid production sequences");
        validProductionLines.setFocusable(false);
        validProductionLines.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        validProductionLines.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(validProductionLines);

        pricesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prices.png"))); // NOI18N
        pricesButton.setToolTipText("Market Prices");
        pricesButton.setFocusable(false);
        pricesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pricesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(pricesButton);

        sell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cart.png"))); // NOI18N
        sell.setToolTipText("Sell warehouse");
        sell.setFocusable(false);
        sell.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sell.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(sell);

        lab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab.png"))); // NOI18N
        lab.setToolTipText("Research lab");
        lab.setFocusable(false);
        lab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(lab);

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.png"))); // NOI18N
        play.setToolTipText("Play game");
        play.setFocusable(false);
        play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        play.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(play);

        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pause.png"))); // NOI18N
        pause.setToolTipText("Pause game");
        pause.setFocusable(false);
        pause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(pause);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exit.setToolTipText("Exit game");
        exit.setFocusable(false);
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(exit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton info;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton lab;
    private javax.swing.JButton lineElementsMarket;
    private javax.swing.JToggleButton pause;
    private javax.swing.JToggleButton play;
    private javax.swing.JButton pricesButton;
    private javax.swing.JButton rawMaterialsMarket;
    private javax.swing.JButton sell;
    private javax.swing.JButton validProductionLines;
    // End of variables declaration//GEN-END:variables

}
