package view.game;

import javax.swing.JButton;
import javax.swing.JToggleButton;

public class ToolBarPanel extends javax.swing.JPanel {

    /** Creates new form ToolBarPanel */
    public ToolBarPanel() {
        initComponents();
    }

    public JButton getLineElementsMarketButton() {
        return this.lineElementsMarket;
    }

    public JButton getRawMaterialsMarketButton() {
        return this.rawMaterialsMarket;
    }

    public JButton getValidProductionLinesButton() {
        return this.validProductionLines;
    }

    public JButton getTechnologyTreeButton() {
        return this.technologyTree;
    }

    public JButton getSellButton() {
        return this.sell;
    }

    public JToggleButton getPauseButton() {
        return this.pause;
    }

    public JToggleButton getPlayButton() {
        return this.play;
    }

    public JButton getGroundSelectionMenuButton() {
        return this.grounds;
    }

    public JButton getExitButton() {
        return this.exit;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lineElementsMarket = new javax.swing.JButton();
        rawMaterialsMarket = new javax.swing.JButton();
        validProductionLines = new javax.swing.JButton();
        technologyTree = new javax.swing.JButton();
        sell = new javax.swing.JButton();
        play = new javax.swing.JToggleButton();
        pause = new javax.swing.JToggleButton();
        grounds = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        lineElementsMarket.setText("Line market");
        lineElementsMarket.setToolTipText(LINE_ELEMENTS_MARKET);
        lineElementsMarket.setFocusable(false);
        lineElementsMarket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lineElementsMarket.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(lineElementsMarket);

        rawMaterialsMarket.setText("Raw-Mat Market");
        rawMaterialsMarket.setToolTipText(RAW_MATERIALS_MARKET);
        rawMaterialsMarket.setFocusable(false);
        rawMaterialsMarket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rawMaterialsMarket.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(rawMaterialsMarket);

        validProductionLines.setText("Valid Prod");
        validProductionLines.setToolTipText(VALID_PRODUCTION_LINES);
        validProductionLines.setFocusable(false);
        validProductionLines.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        validProductionLines.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(validProductionLines);

        technologyTree.setText("Lab");
        technologyTree.setToolTipText(TECHNOLOGY_TREE);
        technologyTree.setFocusable(false);
        technologyTree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        technologyTree.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(technologyTree);

        sell.setText("Sell");
        sell.setToolTipText(SELL);
        sell.setFocusable(false);
        sell.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sell.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(sell);

        play.setText("Play");
        play.setToolTipText(PLAY);
        play.setFocusable(false);
        play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        play.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(play);

        pause.setText("Pause");
        pause.setToolTipText(PAUSE);
        pause.setFocusable(false);
        pause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(pause);

        grounds.setText("Grounds");
        grounds.setToolTipText(GROUNDS);
        grounds.setFocusable(false);
        grounds.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        grounds.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(grounds);

        exit.setText("Exit");
        exit.setToolTipText(EXIT);
        exit.setFocusable(false);
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(exit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private static final String LINE_ELEMENTS_MARKET = "Line elements market";
    private static final String RAW_MATERIALS_MARKET = "Raw materials market";
    private static final String VALID_PRODUCTION_LINES = "Valid production lines";
    private static final String TECHNOLOGY_TREE = "Technology tree";
    private static final String SELL = "Sell Warehouse";
    private static final String PAUSE = "Pause game";
    private static final String PLAY = "Play game";
    private static final String GROUNDS = "Ground's selection menu";
    private static final String EXIT = "Exit game";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton grounds;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton lineElementsMarket;
    private javax.swing.JToggleButton pause;
    private javax.swing.JToggleButton play;
    private javax.swing.JButton rawMaterialsMarket;
    private javax.swing.JButton sell;
    private javax.swing.JButton technologyTree;
    private javax.swing.JButton validProductionLines;
    // End of variables declaration//GEN-END:variables

}
